from typing import Dict, List

languages: Dict[str, List[str]] = {
    "korean": [
        "Korean",
        "English",
    ],
    "latin": [
        "French",
        "German",
        "Afrikaans",
        "Italian",
        "Spanish",
        "Bosnian",
        "Portuguese",
        "Czech",
        "Welsh",
        "Danish",
        "Estonian",
        "Irish",
        "Croatian",
        "Uzbek",
        "Hungarian",
        "Serbian (Latin)",
        "Indonesian",
        "Occitan",
        "Icelandic",
        "Lithuanian",
        "Maori",
        "Malay",
        "Dutch",
        "Norwegian",
        "Polish",
        "Slovak",
        "Slovenian",
        "Albanian",
        "Swedish",
        "Swahili",
        "Tagalog",
        "Turkish",
        "Latin",
        "Azerbaijani",
        "Kurdish",
        "Latvian",
        "Maltese",
        "Pali",
        "Romanian",
        "Vietnamese",
        "Finnish",
        "Basque",
        "Galician",
        "Luxembourgish",
        "Romansh",
        "Catalan",
        "Quechua",
    ],
    "eslav": [
        "Russian",
        "Belarusian",
        "Ukrainian",
        "English"
    ],
    "th": [
        "Thai",
        "English",
    ],
    "el": [
        "Greek",
        "English",
    ],
    "en": [
        "English",
    ],
    "cyrillic": [
        "Russian",
        "Belarusian",
        "Ukrainian",
        "Serbian (Cyrillic)",
        "Bulgarian",
        "Mongolian",
        "Abkhazian",
        "Adyghe",
        "Kabardian",
        "Avar",
        "Dargin",
        "Ingush",
        "Chechen",
        "Lak",
        "Lezgin",
        "Tabasaran",
        "Kazakh",
        "Kyrgyz",
        "Tajik",
        "Macedonian",
        "Tatar",
        "Chuvash",
        "Bashkir",
        "Malian",
        "Moldovan",
        "Udmurt",
        "Komi",
        "Ossetian",
        "Buryat",
        "Kalmyk",
        "Tuvan",
        "Sakha",
        "Karakalpak",
        "English"
    ],
    "arabic": [
        "Arabic",
        "Persian",
        "Uyghur",
        "Urdu",
        "Pashto",
        "Kurdish",
        "Sindhi",
        "Balochi",
        "English"
    ],
    "devanagari": [
        "Hindi",
        "Marathi",
        "Nepali",
        "Bihari",
        "Maithili",
        "Angika",
        "Bhojpuri",
        "Magahi",
        "Santali",
        "Newari",
        "Konkani",
        "Sanskrit",
        "Haryanvi",
        "English"
    ],
    "ta": [
        "Tamil",
        "English",
    ],
    "te": [
        "Telugu",
        "English",
    ],
}
