from typing import Dict, List

languages: Dict[str, List[str]] = {
    "korean": ["ko", "en"],
    "latin": [
        "fr",
        "de",
        "af",
        "it",
        "es",
        "bs",
        "pt",
        "cs",
        "cy",
        "da",
        "et",
        "ga",
        "hr",
        "uz",
        "hu",
        "sr",
        "id",
        "oc",
        "is",
        "lt",
        "mi",
        "ms",
        "nl",
        "no",
        "pl",
        "sk",
        "sl",
        "sq",
        "sv",
        "sw",
        "tl",
        "tr",
        "la",
        "az",
        "ku",
        "lv",
        "mt",
        "pi",
        "ro",
        "vi",
        "fi",
        "eu",
        "gl",
        "lb",
        "rm",
        "ca",
        "qu",
    ],
    "eslav": ["ru", "be", "uk", "en"],
    "th": ["th", "en"],
    "el": ["el", "en"],
    "en": ["en"],
    "cyrillic": [
        "ru",
        "be",
        "uk",
        "sr",
        "bg",
        "mn",
        "ab",
        "ady",
        "kbd",
        "av",
        "dar",
        "inh",
        "ce",
        "lbe",
        "lez",
        "tab",
        "kk",
        "ky",
        "tg",
        "mk",
        "tt",
        "cv",
        "ba",
        "ml",
        "md",
        "udm",
        "kv",
        "os",
        "bu",
        "xal",
        "ty",
        "sah",
        "kaa",
    ],
    "arabic": ["ar", "fa", "ug", "ur", "ps", "ku", "sd", "bal"],
    "devanagari": [
        "hi",
        "mr",
        "ne",
        "bh",
        "mai",
        "anp",
        "bho",
        "mag",
        "sat",
        "new",
        "kok",
        "sa",
        "ha",
    ],
    "ta": ["ta", "en"],
    "te": ["te", "en"],
}
